### ISSUE TITLE
Agregar link correcto de donaciones a la página de donar

### ISSUE THREAD

**Issue by Alais29** [JSConfCL/TechTon-landing#137]
https://www.figma.com/file/BucpDF5NfsB3eX7ouVvaLf/418-especial---ayuda?type=design&node-id=415%3A4786&mode=design&t=Wrddcvq0FmYjevHX-1

Desktop

![Image](https://github.com/JSConfCL/TechTon-landing/assets/62083149/b7df24f7-9c51-494f-9a8c-b61b57fe8880)

Enlace Nacional: https://link.mercadopago.cl/jscl
Enlace Internacional: https://buy.stripe.com/dR64jQcNI2Up0OkdR0

**Comment by fabianhtml** [comment]
Link de pago Internacional: https://buy.stripe.com/dR64jQcNI2Up0OkdR0

**Comment by joseglego** [comment]
Agregados detalles que estaban en la tarjeta duplicada:
