### ISSUE TITLE
Actualizar botones de donar (nuevos medios de donación)

### ISSUE THREAD

**Issue by Dereemii** [JSConfCL/TechTon-landing#144]
https://www.figma.com/file/BucpDF5NfsB3eX7ouVvaLf/418-especial---ayuda?type=design&node-id=415%3A4786&mode=design&t=Wrddcvq0FmYjevHX-1

Desktop

![Image](https://github.com/JSConfCL/TechTon-landing/assets/62083149/b7df24f7-9c51-494f-9a8c-b61b57fe8880)

**Comment by joseglego** [comment]
Cerrando esto como "duplicado", agregando detalles en #137
