### ISSUE TITLE
BUG: Contenido de la página "Donar" se ve muy largo en pantallas grandes

### ISSUE THREAD

**Issue by daraletdev** [JSConfCL/TechTon-landing#167]
Acortar el contenido del texto: "Todo el dinero será dirigido a Bomberos de Chile. El botón de donar te llevará a Mercado Pago y está disponible para donaciones en países donde esté habilitado."
para que no se vea tan largo y sea más legible.

![Image](https://github.com/JSConfCL/TechTon-landing/assets/83615859/e33d59e2-f971-4abf-8081-c606c21ecb2c)

**Comment by Dereemii** [comment]
se fixeo en otro 
![image](https://github.com/JSConfCL/TechTon-landing/assets/62083149/f5017ed4-1da3-419d-b68b-1b512765ed2f)
