### ISSUE TITLE
logo en el header tiene baja calidad

### ISSUE THREAD

**Issue by fforres** [JSConfCL/TechTon-landing#187]
![image](https://github.com/JSConfCL/TechTon-landing/assets/952992/db76b70c-04f3-496d-b06d-2421264c15c9)

Se ve blurry :(

**Comment by Dereemii** [comment]
Se arregló en un fix anterior , los issues sumalos plis en el project :3  https://github.com/orgs/JSConfCL/projects/9/views/1
