### ISSUE TITLE
Fix CSS: [Navbar] Agregar opacidad/ transparencia + borde

### ISSUE THREAD

**Issue by Dereemii** [JSConfCL/TechTon-landing#206]
Navbar tiene un tono un poco diferente además de un borde con color
 

![Image](https://github.com/JSConfCL/TechTon-landing/assets/62083149/ba45196a-b6cb-45bb-8540-d769b0dd22e0)

![Image](https://github.com/JSConfCL/TechTon-landing/assets/62083149/048a71dd-ed06-4034-b893-e8619e394788)

**Comment by Alais29** [comment]
@Dereemii el fondo que tiene actualmente es el que sale en el figma 



![Image](https://github.com/JSConfCL/TechTon-landing/assets/28829550/d55dc7a4-7112-41fc-986e-b1f280d21c27)
