### ISSUE TITLE
Feat: ¡Mira cuánto llevamos!

### ISSUE THREAD

**Issue by Dereemii** [JSConfCL/TechTon-landing#212]
Se modifican estilos y además se añaden textos más accesibles para los usuarios

Desktop:

![Image](https://github.com/JSConfCL/TechTon-landing/assets/62083149/5292b75c-7dde-4d6f-a790-4cf6e7cc4168)

Mobile:

![Image](https://github.com/JSConfCL/TechTon-landing/assets/62083149/6cfd65c8-a8fd-47d4-8a3e-9ef5b0e41630)

**Comment by Alais29** [comment]
El cambio de diseño esta en la rama https://github.com/JSConfCL/TechTon-landing/tree/feat/212

Pero no se tiene un link para mostrar lo recaudado

**Comment by Dereemii** [comment]
ya no aplica
