### ISSUE TITLE
Feat: Agregar enlaces a los logos de comunidades

### ISSUE THREAD

**Issue by clsource** [JSConfCL/TechTon-landing#248]
Para permitir que las personas puedan conocer un poco más las comunidades sería
bueno que cada logotipo al hacer click abriera la URL de la comunidad.

- https://github.com/JSConfCL/TechTon-landing/blob/main/src/communities/communities.json
- https://github.com/JSConfCL/TechTon-landing/blob/main/src/app/nosotros/page.js#L64

**Comment by Dereemii** [comment]
Se cerró en el PR --> https://github.com/JSConfCL/TechTon-landing/pull/253


Si necesitan crear issues, por favor hacerlo a través de Projects 😄
Para una revisión más fácil del status 💚 

https://github.com/orgs/JSConfCL/projects/9/views/1?pane=info


Gracias
