### ISSUE TITLE
Ajustar ancho de contenido de texto principal para desktop

### ISSUE THREAD

**Issue by odracirdev** [JSConfCL/TechTon-landing#26]
![WhatsApp Image 2024-02-05 at 08 04 35_254cbdc7](https://github.com/JSConfCL/TechTon-landing/assets/84311660/ee56f963-3f33-482c-bd8f-50b63bb1f710)

Si no hay más información lo ideal es que el texto del párrafo se vea con el mismo ancho que el contador para no romper la armonía del diseño.

**Comment by Dereemii** [comment]
> ![WhatsApp Image 2024-02-05 at 08 04 35_254cbdc7](https://private-user-images.githubusercontent.com/84311660/302267772-ee56f963-3f33-482c-bd8f-50b63bb1f710.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzIwNDksIm5iZiI6MTcwNzEzMTc0OSwicGF0aCI6Ii84NDMxMTY2MC8zMDIyNjc3NzItZWU1NmY5NjMtM2YzMy00ODJjLWJkOGYtNTBiNjNiYjFmNzEwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDExMTU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ODVmYmI5NTBmMDFkOWZjNThmNzZmZTEzZjEyYzlkMWU2NTNjZGU1OTQ0NjdiODhkMmE2YzQyYzFjMDQ1NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JxP-Vru3pOiBHGJ11-4a_H1xg_p_0YzqTOdbuqQoMGM)
> 
> Si no hay más información lo ideal es que el texto del párrafo se vea con el mismo ancho que el contador para no romper la armonía del diseño.

En realidad el texto debe adjustarse al diseño actualmente tiene un ancho predefinido debe estar alrededor de los 850px para desktop
![image](https://github.com/JSConfCL/TechTon-landing/assets/62083149/b15e4a6a-1ded-423c-a327-986d2cd58626)
