### ISSUE TITLE
Crear JSON con charlistas y horarios

### ISSUE THREAD

**Issue by frani-be** [JSConfCL/TechTon-landing#47]
En base a la información de los charlistas que tenemos actualmente, se debe crear un json consumible con los siguientes atributos:

`name, topic, image, startHour, endHour, community`

**Comment by DvdQzd** [comment]
@frani-be En que formato necesitas `startHour` y `endHour` ?

**Comment by frani-be** [comment]
@DvdQzd asumo que podría ser ISO 8601

**Comment by frani-be** [comment]
@DvdQzd agregarle por favor comunidad
