### ISSUE TITLE
Crear componente de Tabs para la página de Agenda

### ISSUE THREAD

**Issue by Alais29** [JSConfCL/TechTon-landing#53]
- Debe verse correctamente en Desktop y Mobile 
- Componente en Tailwind para utilizar de referencia: [https://www.material-tailwind.com/docs/html/tabs](https://www.material-tailwind.com/docs/html/tabs)
- En virtud del tiempo usar el componente mencionado y ajustar a los colores y textos actuales del diseño

**Comment by daraletdev** [comment]
@Alais29  No se puede personalizar el color blanco de la píldora _(la que se mueve de un lado a otro)_ (se mantiene blanco y no es un elemento que esté en el HTML ni con una clase para modificarlo) Por más que hago - inspeccionar - no sale nada acerca del color

Según lo que veo hay dos opciones:
- Dejar el blanco y cambiar el diseño para que se ajuste
- Usar esta alternativa (más flexible en diseño pero un poco + compleja) https://www.material-tailwind.com/docs/react/tabs
