### ISSUE TITLE
Docs: Modificar horario de agenda en README.md

### ISSUE THREAD

**Issue by Dereemii** [JSConfCL/TechTon-landing#57]
Se debe corregir la hora de agenda para ambos días:

Viernes desde las 13:00
Sábado desde las 7:00 AM

![Image](https://github.com/JSConfCL/TechTon-landing/assets/62083149/a299c689-5431-4d64-ae48-5c22304c4d7d)

**Comment by odracirdev** [comment]
Se actualiza la hora en la PR https://github.com/JSConfCL/TechTon-landing/pull/62
