### ISSUE TITLE
BUG: Ajustar ancho del footer en mobile

### ISSUE THREAD

**Issue by odracirdev** [JSConfCL/TechTon-landing#64]
En distintas resoluciones móviles el ancho del footer no llega a cubrir todo el ancho.

![image](https://github.com/JSConfCL/TechTon-landing/assets/84311660/79ffd5be-efd0-4486-b9d6-e8f0db04ad2e)

![image](https://github.com/JSConfCL/TechTon-landing/assets/84311660/dcdcea87-40f0-41b5-a970-711d2c8482ae)

![image](https://github.com/JSConfCL/TechTon-landing/assets/84311660/9c7bbe28-626e-4e3c-b714-84f8174b2c93)

**Comment by daraletdev** [comment]
En versión móvil existe un overflow horizontal por los elementos **titulo, los botones** . Si se eliminan esos elementos al inspeccionar elemento ya no se genera ese efecto. 
-> Se deben ajustar los botones para que sean responsivos (flex-col en movil, flex-row en las siguientes pantallas)
-> Se debe hacer más pequeño el título de TechTón para que quepa en la pantalla y no provoque overflow

**Comment by Dereemii** [comment]
ok arreglado c:
